// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "project3/group3/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProductData is an autogenerated mock type for the ProductData type
type ProductData struct {
	mock.Mock
}

// DeleteProductDB provides a mock function with given fields: productID
func (_m *ProductData) DeleteProductDB(productID int) (int, error) {
	ret := _m.Called(productID)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(productID)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: idProduct
func (_m *ProductData) GetUser(idProduct int) (domain.Product, error) {
	ret := _m.Called(idProduct)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(int) domain.Product); ok {
		r0 = rf(idProduct)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(idProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertProductDB provides a mock function with given fields: newProduct
func (_m *ProductData) InsertProductDB(newProduct domain.Product) (domain.Product, error) {
	ret := _m.Called(newProduct)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(domain.Product) domain.Product); ok {
		r0 = rf(newProduct)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Product) error); ok {
		r1 = rf(newProduct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectData provides a mock function with given fields: limit, offset
func (_m *ProductData) SelectData(limit int, offset int) ([]domain.Product, error) {
	ret := _m.Called(limit, offset)

	var r0 []domain.Product
	if rf, ok := ret.Get(0).(func(int, int) []domain.Product); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectDataById provides a mock function with given fields: id
func (_m *ProductData) SelectDataById(id int) (domain.Product, error) {
	ret := _m.Called(id)

	var r0 domain.Product
	if rf, ok := ret.Get(0).(func(int) domain.Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateData provides a mock function with given fields: data, idProduct, idFromToken
func (_m *ProductData) UpdateData(data map[string]interface{}, idProduct int, idFromToken int) (int, error) {
	ret := _m.Called(data, idProduct, idFromToken)

	var r0 int
	if rf, ok := ret.Get(0).(func(map[string]interface{}, int, int) int); ok {
		r0 = rf(data, idProduct, idFromToken)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}, int, int) error); ok {
		r1 = rf(data, idProduct, idFromToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductData interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductData creates a new instance of ProductData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductData(t mockConstructorTestingTNewProductData) *ProductData {
	mock := &ProductData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
